version: '3.8'

services:
  mysql:
    container_name: init-mysql
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: init
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
    ports: [ "3306:3306" ]
    volumes:
      - ./docker/db/mysql/data:/var/lib/mysql
      - ./docker/db/mysql/config:/etc/mysql/conf.d
      - ./docker/db/mysql/init:/docker-entrypoint-initdb.d
    networks: [ init-db ]
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234" ]
      timeout: 20s
      retries: 10

networks:
  init-db:

