spring:
  config:
    import: optional:file:.env[.properties]

  sql:
    init:
      mode: always

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/init}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

oauth2:
  client:
    provider:
      kakao:
        client-id: ${KAKAO_CLIENT_ID:example-client-id}
        client-secret: ${KAKAO_CLIENT_SECRET:example-secret-key}
        jwks-uri: ${KAKAO_JWKS_URI:https://kauth.kakao.com/.well-known/jwks.json}
        token-uri: ${KAKAO_TOKEN_URI:https://kauth.kakao.com/oauth/token}
        issuer: ${KAKAO_ISS:https://kauth.kakao.com}
        nonce: ${KAKAO_NONCE:example-nonce}
        redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:8080}
      google:
        client-id: ${GOOGLE_CLIENT_ID:example-client-id}
        client-secret: ${GOOGLE_CLIENT_SECRET:example-secret-key}
        jwks-uri: ${GOOGLE_JWKS_URI:https://www.googleapis.com/oauth2/v3/certs}
        token-uri: ${GOOGLE_TOKEN_URI:https://oauth2.googleapis.com/token}
        issuer: ${GOOGLE_ISS:https://accounts.google.com}
        nonce: ${GOOGLE_NONCE:example-nonce}
        redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8080}

jwt:
  secret-key:
    access-token: ${JWT_ACCESS_SECRET_KEY:exampleJwtAccessSecretKeyInitSystemAccessSecretKeyForPadding}
    refresh-token: ${JWT_REFRESH_SECRET_KEY:exampleJwtRefreshSecretKeyInitSystemRefreshSecretKeyForPadding}
  expiration-time:
    access-token: ${JWT_ACCESS_EXPIRATION_TIME:1800000} # 30m (30 * 60 * 1000) 1800000
    refresh-token: ${JWT_REFRESH_EXPIRATION_TIME:604800000} # 7d (7 * 24 * 60 * 60 * 1000)

# swagger에서 자동으로 error response를 생성하지 않도록 설정
springdoc:
  override-with-generic-response: false

openai:
  api-key: ${OPENAI_API_KEY}
  embedding-model: ${OPENAI_EMBEDDING_MODEL}
  chat-model: ${OPENAI_CHAT_MODEL}

logging:
  level:
    com.init: DEBUG